import {
  EMAIL,
  GITHUB_URL,
  GRADUATION,
  LINKEDIN,
  LOCATION,
  NAME,
  PHONE,
  ROLE,
  SCHOOL,
} from "@/lib/site";

export const RESUME_TEXT_LINES = [
  NAME,
  `${EMAIL} | ${PHONE} | ${LINKEDIN} | ${GITHUB_URL}`,
  "",
  "EDUCATION",
  `${SCHOOL}, College of Engineering | ${LOCATION}`,
  `B.S. in Industrial Distribution | Minors: Computer Science & Statistics | Expected: ${GRADUATION}`,
  "Honors: Dean's List, Century Scholars",
  "",
  "EXPERIENCE",
  "QTS Data Centers | May 2025 - May 2026",
  `${ROLE} Intern | October 2025 - May 2026 | Remote`,
  "- Optimized and maintained MOP/SOP digitization platform, reducing Docker image size by 40% and cutting AWS compute and storage costs across production workloads.",
  "- Eliminated 10+ hours of weekly manual entry by automating Oracle Cloud Fusion change orders with Playwright-based procurement workflows.",
  "- Reduced Lambda and S3 request overhead by parallelizing S3 reads, aligning connection pools, and replacing unconditional ECS calls with a two-phase search pipeline.",
  "- Shipped Terraform-managed Python services on AWS for file upload, parsing, and validation, consumed by an Angular/Nx micro-frontend for data-center operations.",
  "Machine Learning & Data Science Intern | May 2025 - October 2025 | Suwanee, GA",
  "- Built an electrical diagram processing pipeline using computer vision and R-tree spatial indexing to extract asset relationships, with electrical flow checks to detect and resolve mismatches.",
  "- Automated the creation of 6,000+ asset relationships per site and consolidated alarms, reducing time to isolate root causes by 80%.",
  "- Validated electrical-flow relationships and anomaly-detection outputs against operational baselines, surfacing data-integrity issues across 30+ data-center locations.",
  `${SCHOOL} | August 2024 - December 2025`,
  `Teaching Assistant, ENGR 102/216 & CSCE 111 | ${LOCATION}`,
  "- Supported 200+ students in Python and Java via office hours and debugging sessions; delivered guest lectures during instructor absences and authored supplemental practice problems.",
  "",
  "PROJECTS",
  `droids-mem - Persistent Memory Layer for AI Agents | ${GITHUB_URL}/droids-mem`,
  "- Shipped a local-first persistent memory service for AI coding agents as a single Go binary with an MCP interface, CodeQL analysis, and end-to-end tests.",
  "- Sustained sub-100ms p95 search with SQLite/FTS5, two-layer deduplication, and an 18-pattern PII scrub pipeline without CGO.",
  "TAMIDS 2026 Finalist - NFL Draft Analytics Platform",
  "- Architected a DuckDB/Parquet medallion lake and Neo4j identity graph across 15 datasets from 2000-2024, linking over 85% of combine and 90% of draft records.",
  "- Delivered explainable player grades and draft recommendations with XGBoost, SHAP, and CVXPY through natural-language workflows backed by Redis/SQLite state.",
  "Music Discovery Engine",
  "- Built a music recommendation engine doubling NDCG@10 over default weights by tuning an ALS recommender's sonic-fit, novelty, emotional-fit, and familiarity signals on the Million Song Dataset.",
  "- Improved recommendation diversity and personalization with MMR re-ranking, per-artist caps, and BIC-selected Gaussian Mixture personas that outperformed fixed-K baselines.",
  "TAMIDS Cyberwise 2025 Finalist (Graduate Division) - Security Analytics Framework (competed as undergraduate)",
  "- Mapped DDoS attack phases with graph-based attack-path visualization and anomaly detection across 476,000+ flagged events.",
  "",
  "LEADERSHIP & ACTIVITIES",
  `Vice President & IT Officer, QuantA&M - ${LOCATION} | January 2023 - Present`,
  "- Managed industry partnerships, coordinated a speaker series, and oversaw operations for 50+ members across a quantum computing student organization; designed and maintained the full-stack club website.",
  "",
  "SKILLS",
  "Languages: Go, Python, TypeScript, SQL, Java, R, C++",
  "Cloud & Tools: AWS (EC2, S3, Lambda, ECS), Docker, Terraform, DuckDB, Redis, Git, Linux",
  "Frameworks & QA: FastAPI, Flask, React, Angular/Nx, Playwright, CI/CD (GitHub Actions), CodeQL",
] as const;
